# Generated by Django 4.0.2 on 2022-02-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='username',
            new_name='name',
        ),
    ]
