# Generated by Django 4.0.2 on 2022-02-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_rename_username_visitor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(max_length=6),
        ),
    ]
